[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "simple_protocol"
publish = false
version = "0.1.0"

[dependencies]
bevy_wasm_shared.workspace = true
bevy.workspace = true
serde.workspace = true
