[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "simple"
publish = false
version = "0.1.0"

[dependencies]
bevy = { workspace = true, features = ["bevy_winit"] }
bevy_wasm.workspace = true
simple_protocol.workspace = true
