[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "mod_with_bevy"
publish = false
version = "0.1.0"

[lib]
# Generate a `.wasm` file instead of a dll
crate-type = ["cdylib"]

[dependencies]
bevy.workspace = true
cubes_protocol.workspace = true

bevy_wasm_sys.workspace = true
