[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "cubes_protocol"
publish = false
version = "123.456.789"

[dependencies]
bevy.workspace = true
bevy_wasm_shared.workspace = true
serde = { version = "1.0", features = ["derive"] }
