[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "mod_without_bevy"
publish = false
version = "0.1.0"

[lib]
# Generate a `.wasm` file instead of a dll
crate-type = ["cdylib"]

[dependencies]
cubes_protocol = { path = "../cubes_protocol" }

bevy_wasm_sys_core.workspace = true
